server:
  port: ${SERVER_PORT:15001}

management:
  server:
    port: ${MANAGEMENT_PORT:15002}
  endpoint:
    health:
      enabled: true
      show-details: always

spring:
  datasource:
    url: jdbc:mysql://192.168.118.8:23306/winstar_communal_coupon?characterEncoding=utf-8
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1900000
      maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql

logging:
  level:
    root: info

---
spring:
  profiles: prod
  datasource:
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1900000
      maximum-pool-size: 500
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql

server:
  port: ${SERVER_PORT:12002}

management:
  server:
    port: ${MANAGEMENT_PORT:12003}
  endpoint:
    health:
      enabled: true
      show-details: always

logging:
  level:
    root: info
