server:
  port: ${SERVER_PORT:12002}

management:
  server:
    port: ${MANAGEMENT_PORT:12003}
  endpoint:
    health:
      enabled: true
      show-details: always

spring:
  datasource:
    url: jdbc:mysql://192.168.118.8:23306/winstar_communal_coupon?characterEncoding=utf-8
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1900000
      maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}

  client:
    serviceUrl:
      defaultZone:  http://winstar:123456@192.168.118.101:19000/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    root: info

---
spring:
  profiles: prod
  datasource:
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1900000
      maximum-pool-size: 500
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql

server:
  port: ${SERVER_PORT:12002}

management:
  server:
    port: ${MANAGEMENT_PORT:12003}
  endpoint:
    health:
      enabled: true
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: ${{EUREKA_SERVER_LIST}:http://winstar:123456@10.0.20.85:9090/eureka/,http://winstar:123456@10.0.20.86:9090/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}

logging:
  level:
    root: info
